name: Draw Keymap

on:
  push:
    branches:
      - main
    paths:
      - 'config/*.keymap'
      - 'keymap_drawer.config.yaml'
  workflow_dispatch:

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "assets"
      parse_args: ""
      draw_args: ""

  rename:
    runs-on: ubuntu-latest
    needs: draw
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Rename keymap file
        run: |
          git pull
          if [ -f "assets/corne.svg" ]; then
            cp assets/corne.svg assets/my_keymap.svg
            git rm -f assets/corne.svg
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add assets/my_keymap.svg
            git diff --staged --quiet || git commit -m "Rename keymap diagram to my_keymap.svg [skip ci]"
            git push
          fi
